In [66]:
'''
HW Questions (Numpy):
1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
2. Find common elements between A and B. [Hint: Intersection of two sets]
3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
'''

"\nHW Questions (Numpy):\n1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.\n2. Find common elements between A and B. [Hint: Intersection of two sets]\n3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]\n4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0\nurl = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'\niris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])\n"

In [67]:
import pandas as pd
import numpy as np

In [68]:
# 1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

A = np.array([[1,22],[44,5]])
B = np.array([[11,22],[44,55]])

print('vstack = \n',np.vstack((A,B)))
print('hstack = \n',np.hstack((A,B)))

vstack = 
 [[ 1 22]
 [44  5]
 [11 22]
 [44 55]]
hstack = 
 [[ 1 22 11 22]
 [44  5 44 55]]


In [69]:
# 2. Find common elements between A and B. [Hint: Intersection of two sets]

common_elements = np.intersect1d(A, B)
print('Common elements:', common_elements)

Common elements: [22 44]


In [70]:
# 3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

numbers_in_range = A[(A >= 5) & (A <= 10)]
print('Numbers in A between 5 and 10:', numbers_in_range)

Numbers in A between 5 and 10: [5]


In [71]:
# 4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

local_path = './iris.data'
iris_2d = np.genfromtxt(local_path, delimiter=',', dtype='float', usecols=[0,1,2,3])

filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print(filtered_rows)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [72]:
'''
HW Questions (Pandas):
1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
2. Replace missing values in Min.Price and Max.Price columns with their respective mean.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
3. How to get the rows of a dataframe with row sum > 100?
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
'''

"\nHW Questions (Pandas):\n1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).\ndf = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')\n2. Replace missing values in Min.Price and Max.Price columns with their respective mean.\ndf = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')\n3. How to get the rows of a dataframe with row sum > 100?\ndf = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))\n"

In [73]:
df = pd.read_csv('./Cars93_miss.csv')
df.head(10)

Manufacturer       Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura     Integra    Small       12.9   15.9       18.8      25.0   
1          NaN      Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi          90  Compact       25.9   29.1       32.3      20.0   
3         Audi         100  Midsize        NaN   37.7       44.6      19.0   
4          BMW        535i  Midsize        NaN   30.0        NaN      22.0   
5        Buick     Century  Midsize       14.2   15.7       17.3      22.0   
6        Buick     LeSabre    Large       19.9   20.8        NaN      19.0   
7        Buick  Roadmaster    Large       22.6   23.7       24.9      16.0   
8        Buick     Riviera  Midsize       26.3   26.3       26.3      19.0   
9     Cadillac     DeVille    Large       33.0   34.7       36.3      16.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   
5         31.0         Driver only        NaN  ...        6.0   189.0   
6         28.0         Driver only      Front  ...        6.0   200.0   
7         25.0         Driver only       Rear  ...        6.0   216.0   
8         27.0         Driver only      Front  ...        5.0   198.0   
9         25.0         Driver only      Front  ...        6.0   206.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   
5      105.0   69.0         41.0           28.0          16.0     NaN   
6      111.0   74.0         42.0           30.5          17.0  3470.0   
7      116.0   78.0         45.0           30.5          21.0  4105.0   
8      108.0    NaN         41.0           26.5          14.0  3495.0   
9      114.0   73.0         43.0           35.0          18.0  3620.0   

    Origin              Make  
0  non-USA     Acura Integra  
1  non-USA      Acura Legend  
2  non-USA           Audi 90  
3  non-USA          Audi 100  
4  non-USA          BMW 535i  
5      USA     Buick Century  
6      USA     Buick LeSabre  
7      USA  Buick Roadmaster  
8      USA     Buick Riviera  
9      USA  Cadillac DeVille  

[10 rows x 27 columns]

In [74]:
# 1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

filtered_df = df.loc[0::20, ['Manufacturer', 'Model', 'Type']]
print(filtered_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [75]:
# 2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

df.head(15)

/var/folders/jq/y2kzd93d76jbj3szdx797mkh0000gn/T/ipykernel_18098/3403316619.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
/var/folders/jq/y2kzd93d76jbj3szdx797mkh0000gn/T/ipykernel_18098/3403316619.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting

Manufacturer       Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura     Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN      Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi          90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi         100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW        535i  Midsize  17.118605   30.0  21.459091      22.0   
5         Buick     Century  Midsize  14.200000   15.7  17.300000      22.0   
6         Buick     LeSabre    Large  19.900000   20.8  21.459091      19.0   
7         Buick  Roadmaster    Large  22.600000   23.7  24.900000      16.0   
8         Buick     Riviera  Midsize  26.300000   26.3  26.300000      19.0   
9      Cadillac     DeVille    Large  33.000000   34.7  36.300000      16.0   
10     Cadillac     Seville  Midsize  37.500000   40.1  42.700000      16.0   
11    Chevrolet    Cavalier  Compact   8.500000   13.4  18.300000      25.0   
12    Chevrolet     Corsica  Compact  11.400000   11.4  11.400000      25.0   
13    Chevrolet      Camaro   Sporty  13.400000   15.1  16.800000      19.0   
14    Chevrolet      Lumina  Midsize  13.400000   15.9  18.400000       NaN   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
5          31.0         Driver only        NaN  ...        6.0   189.0   
6          28.0         Driver only      Front  ...        6.0   200.0   
7          25.0         Driver only       Rear  ...        6.0   216.0   
8          27.0         Driver only      Front  ...        5.0   198.0   
9          25.0         Driver only      Front  ...        6.0   206.0   
10         25.0  Driver & Passenger      Front  ...        5.0   204.0   
11         36.0                 NaN        NaN  ...        5.0   182.0   
12         34.0         Driver only      Front  ...        5.0   184.0   
13         28.0  Driver & Passenger       Rear  ...        4.0   193.0   
14         29.0                 NaN      Front  ...        6.0     NaN   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
5       105.0   69.0         41.0           28.0          16.0     NaN   
6       111.0   74.0         42.0           30.5          17.0  3470.0   
7       116.0   78.0         45.0           30.5          21.0  4105.0   
8       108.0    NaN         41.0           26.5          14.0  3495.0   
9       114.0   73.0         43.0           35.0          18.0  3620.0   
10      111.0   74.0         44.0           31.0           NaN  3935.0   
11      101.0   66.0         38.0           25.0          13.0  2490.0   
12      103.0   68.0         39.0           26.0           NaN  2785.0   
13      101.0   74.0         43.0           25.0          13.0  3240.0   
14      108.0   71.0          NaN           28.5          16.0  3195.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
5       USA       Buick Century  
6       USA       Buick LeSabre  
7       USA    Buick Roadmaster  
8       USA       Buick Riviera  
9       USA    Cadillac DeVi

In [76]:
# 3. How to get the rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

rows_sum_gt_100 = df[df.sum(axis=1) > 100]
print(rows_sum_gt_100)

     0   1   2   3
0   34  15  21  31
2   24  39  25  27
3   22  24  25  37
4   31  35  27  13
5   32  12  38  34
6   16  35  28  26
7   24  24  38  17
8   31  32  27  39
11  34  18  22  35
