In [56]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a)
print('Shape of a =',a.shape)

b = np.array([[2,4,6],[4,5,2]])
print(b)
print('shape of b =', b.shape)

print(a+b)
print(a*b)

[[1 2 3]
 [4 5 6]]
Shape of a = (2, 3)
[[2 4 6]
 [4 5 2]]
shape of b = (2, 3)
[[ 3  6  9]
 [ 8 10  8]]
[[ 2  8 18]
 [16 25 12]]


In [57]:
c = np.array([[[1,2,3],[1,7,8]],[[2,4,5],[3,4,6]]])
c

array([[[1, 2, 3],
        [1, 7, 8]],

       [[2, 4, 5],
        [3, 4, 6]]])

In [58]:
d = np.array([a,b])
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[2, 4, 6],
        [4, 5, 2]]])

In [59]:
np.ones(2)

array([1., 1.])

In [60]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [61]:
np.random.random(3)

array([0.81297347, 0.25813633, 0.36572441])

In [62]:
np.arange(3,10,5)

array([3, 8])

In [63]:
np.linspace(1,199,100)

array([  1.,   3.,   5.,   7.,   9.,  11.,  13.,  15.,  17.,  19.,  21.,
        23.,  25.,  27.,  29.,  31.,  33.,  35.,  37.,  39.,  41.,  43.,
        45.,  47.,  49.,  51.,  53.,  55.,  57.,  59.,  61.,  63.,  65.,
        67.,  69.,  71.,  73.,  75.,  77.,  79.,  81.,  83.,  85.,  87.,
        89.,  91.,  93.,  95.,  97.,  99., 101., 103., 105., 107., 109.,
       111., 113., 115., 117., 119., 121., 123., 125., 127., 129., 131.,
       133., 135., 137., 139., 141., 143., 145., 147., 149., 151., 153.,
       155., 157., 159., 161., 163., 165., 167., 169., 171., 173., 175.,
       177., 179., 181., 183., 185., 187., 189., 191., 193., 195., 197.,
       199.])

In [64]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.vstack([a,b])
print(c)

[[1 2 3]
 [4 5 6]]


In [65]:
d = np.hstack([a,b])
print(d)

[1 2 3 4 5 6]


In [66]:
a = np.array([[5,1], [4,2], [4,7], [3,2]])
print(a.shape)
print(a.ndim)
print(a.size)

(4, 2)
2
8


In [67]:
a = np.random.random((3,4,2))
print(a.shape)
print(a.ndim)
print(a.size)

(3, 4, 2)
3
24


In [68]:
x = np.array([1,2,3])
y = np.array([1.2,2.3,4.5])
z = np.array([1,2,3],dtype=float)

print(x.dtype)
print(y.dtype)
print(z.dtype)

int64
float64
float64


In [69]:
p = np.arange(1,20,1)
p

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [70]:
p[1::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [71]:
p[0::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [72]:
x = np.random.randint(10,size=(3,5))
print(x)
print(x[:,0])

[[7 5 0 2 5]
 [1 9 3 7 6]
 [9 0 5 4 4]]
[7 1 9]


In [73]:
x2 = np.array([[1,2,3],[4,5,6]])
x2

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
x3 = x2[:,2].copy()
x3

array([3, 6])

In [75]:
grid = np.arange(1,10)
print(grid)

grid_table = grid.reshape(3,3)
print(grid_table)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
# new_grid = np.concatenate([grid,grid], axis=0)

# axis=0 -> Vstack
# axis=1 -> Hstack

In [77]:
print(grid_table.max(axis=0)) # max in colums
print(grid_table.max(axis=1)) # max in rows

[7 8 9]
[3 6 9]


In [78]:
a = np.arange(7)
print(a)
np.where(a>3, a, 10*a) # where(condition, if formula, else formula)

[0 1 2 3 4 5 6]


array([ 0, 10, 20, 30,  4,  5,  6])